//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System;
using global::System.ComponentModel;
using global::System.Data;
using global::System.Data.SqlClient;
using global::System.Collections.Generic;
using global::System.Linq;
using global::System.Xml.Linq;
using global::Inedo.Data;

#pragma warning disable 1591
namespace TheDailyWtf.Data
{
	public static class Tables
	{
		[Obsolete("Articles is obsolete. Use Articles_Extended instead.", true)]
		public class Articles
		{
			public int Article_Id { get; set; }
			public string Article_Slug { get; set; }
			public DateTime? Published_Date { get; set; }
			public string PublishedStatus_Name { get; set; }
			public string Author_Slug { get; set; }
			public string Title_Text { get; set; }
			public string Series_Slug { get; set; }
			public string Body_Html { get; set; }
			public int? Discourse_Topic_Id { get; set; }
			public string Discourse_Topic_Opened { get; set; }
		}
		public class Articles_Extended
		{
			public int Article_Id { get; set; }
			public string Article_Slug { get; set; }
			public DateTime? Published_Date { get; set; }
			public string PublishedStatus_Name { get; set; }
			public string Author_Slug { get; set; }
			public string Title_Text { get; set; }
			public string Series_Slug { get; set; }
			public string Body_Html { get; set; }
			public int? Discourse_Topic_Id { get; set; }
			public string Discourse_Topic_Opened { get; set; }
			public string Author_Display_Name { get; set; }
			public YNIndicator Author_Admin_Indicator { get; set; }
			public string Author_Bio_Html { get; set; }
			public string Author_ShortBio_Text { get; set; }
			public string Author_Image_Url { get; set; }
			public string Series_Title_Text { get; set; }
			public string Series_Description_Text { get; set; }
		}
		public class Authors
		{
			public string Author_Slug { get; set; }
			public string Display_Name { get; set; }
			public byte[] Password_Bytes { get; set; }
			public byte[] Salt_Bytes { get; set; }
			public YNIndicator Admin_Indicator { get; set; }
			public string Bio_Html { get; set; }
			public string ShortBio_Text { get; set; }
			public string Image_Url { get; set; }
		}
		public class FeaturedComments
		{
			public int Article_Id { get; set; }
			public int Discourse_Post_Id { get; set; }
		}
		public class Series
		{
			public string Series_Slug { get; set; }
			public string Title_Text { get; set; }
			public string Description_Text { get; set; }
		}
	}
}
#pragma warning restore 1591
