//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System;


#pragma warning disable 1591
namespace TheDailyWtf.Data
{
	public static class TableNames
	{
		[Obsolete("Articles is obsolete. Use Articles_Extended instead.", true)]
		public const string Articles = "Articles";
		public const string Articles_Extended = "Articles_Extended";
		public const string Authors = "Authors";
		public const string FeaturedComments = "FeaturedComments";
		public const string Series = "Series";
	}
}
#pragma warning restore 1591
